name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Usa la versión de Node que necesitas

      - name: Install dependencies - Backend
        working-directory: ./src/backend
        run: npm install

      - name: Install dependencies - Frontend
        working-directory: ./src/frontend
        run: npm install

      - name: Build Frontend
        working-directory: ./src/frontend
        run: npm run build

      - name: Deploy to EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-west-2" # Cambia por tu región
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: "ec2-user" # O el usuario que uses en tu instancia EC2
        run: |
          # Comprimir archivos
          zip -r deploy.zip src/

          # Subir el archivo comprimido a la instancia EC2
          scp -o StrictHostKeyChecking=no -i my-key.pem deploy.zip $EC2_USER@$EC2_HOST:~

          # Conectarse a EC2 y desplegar
          ssh -o StrictHostKeyChecking=no -i my-key.pem $EC2_USER@$EC2_HOST << 'EOF'
            unzip -o deploy.zip -d ~/app
            cd ~/app/src/backend
            npm install --production
            pm2 restart all # O el comando necesario para reiniciar el backend
EOF
