name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Chequear el código desde el repositorio
    - name: Checkout code
      uses: actions/checkout@v2

    # Paso 2: Crear archivo temporal para la clave PEM de EC2 desde GitHub Secret
    - name: Add EC2 PEM Key
      env:
        EC2_PEM_KEY: ${{ secrets.SMILEYCREATIONS_PEM }}
      run: |
        echo "$EC2_PEM_KEY" > ec2_key.pem
        chmod 400 ec2_key.pem

    # Paso 3: Copiar el backend y el frontend sin comprimir a la instancia EC2
    - name: Deploy Application to EC2
      run: |
        # Crear directorios en EC2 y transferir archivos
        ssh -i ec2_key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} "sudo rm -rf /var/www/backend /var/www/frontend && sudo mkdir -p /var/www/backend /var/www/frontend && sudo chown -R ec2-user:ec2-user /var/www"
        
        # Copiar el backend y frontend completos
        scp -i ec2_key.pem -o StrictHostKeyChecking=no -r ./src/backend/* ec2-user@${{ secrets.EC2_HOST }}:/var/www/backend
        scp -i ec2_key.pem -o StrictHostKeyChecking=no -r ./src/frontend ec2-user@${{ secrets.EC2_HOST }}:/var/www/frontend
    
    # Paso 4: Conectar a la instancia EC2 y ejecutar el build y las instalaciones necesarias
    - name: Build and Install on EC2
      run: |
        ssh -i ec2_key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
          # Cambiar al directorio del backend e instalar dependencias
          cd /var/www/backend
          npm install --production

          # Cambiar al directorio del frontend, instalar dependencias y construir el build
          cd /var/www/frontend
          npm install
          npm run build

          # Mover el build del frontend a la ubicación de despliegue
          mv /var/www/frontend/build /var/www/frontend_deploy

          # Reiniciar NGINX para servir el nuevo frontend
          sudo systemctl restart nginx
        EOF

    # Paso 5: Conectar a la instancia EC2 y reiniciar el backend
    - name: Restart Backend Service on EC2
      run: |
        ssh -i ec2_key.pem -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
          # Asegurarse de que PM2 esté instalado
          if ! command -v pm2 &> /dev/null; then
            npm install -g pm2
          fi

          # Navegar al backend y reiniciar con PM2
          cd /var/www/backend
          pm2 restart backend || pm2 start server.js --name "backend"
        EOF

    # Paso 6: Eliminar el archivo PEM temporal para seguridad
    - name: Clean Up
      run: rm -f ec2_key.pem
